import {EditorState} from "draft-js";

export interface MdeState {
    // This is the only property that the user is supposed to pass. The others are generated by React-Mde
    markdown?: string;
    // Generated by React-Mde
    html?: string;
    // Generated by React-Mde
    draftEditorState?: EditorState;
}
